-- ============================================================
-- 20260720_guild_config_version_history.sql
-- ------------------------------------------------------------
-- Durable per-guild configuration version history.
--
-- Versioned live configuration domains:
-- - guild_configs / guild_config: core Dank Shield settings and Discord IDs;
-- - ticket_categories: active ticket choices plus category-stored form config.
--
-- Goals:
-- - automatically snapshot successful configuration changes;
-- - seed baselines for already-configured guilds, including empty ticket choices;
-- - isolate canonical/legacy config-table histories;
-- - ignore lifecycle/write-audit-only noise;
-- - restore ticket choices atomically in one database transaction;
-- - retain newest 50 versions per guild + configuration domain;
-- - keep RLS enabled with no public policies (service-role bot access only).
--
-- Safe to run more than once.
-- ============================================================

create table if not exists public.guild_config_versions (
    version_id bigint generated by default as identity primary key,
    guild_id text not null,
    config_table text not null default 'guild_configs',
    snapshot jsonb not null,
    source text not null default 'database',
    mode text,
    actor_id text,
    reason text,
    is_manual boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.guild_config_versions
    add column if not exists config_table text not null default 'guild_configs';

create index if not exists idx_guild_config_versions_guild_table_created
    on public.guild_config_versions (
        guild_id,
        config_table,
        created_at desc,
        version_id desc
    );

alter table public.guild_config_versions enable row level security;

-- No public policies are created. Dank Shield uses the Supabase service role.

create or replace function public.normalize_guild_config_snapshot(payload jsonb)
returns jsonb
language plpgsql
immutable
as $$
declare
    result jsonb := coalesce(payload, '{}'::jsonb);
    cleaned jsonb;
begin
    result := result
        - 'updated_at'
        - 'config_last_write_at'
        - 'config_last_write_source'
        - 'config_last_write_mode'
        - 'config_last_write_actor_id'
        - 'config_last_write_reason'
        - 'config_restored_from_version_id';

    if jsonb_typeof(result -> 'settings') = 'object' then
        cleaned := (result -> 'settings')
            - 'config_last_write_at'
            - 'config_last_write_source'
            - 'config_last_write_mode'
            - 'config_last_write_actor_id'
            - 'config_last_write_reason'
            - 'config_restored_from_version_id';
        result := jsonb_set(result, '{settings}', cleaned, false);
    end if;

    if jsonb_typeof(result -> 'config') = 'object' then
        cleaned := (result -> 'config')
            - 'config_last_write_at'
            - 'config_last_write_source'
            - 'config_last_write_mode'
            - 'config_last_write_actor_id'
            - 'config_last_write_reason'
            - 'config_restored_from_version_id';
        result := jsonb_set(result, '{config}', cleaned, false);
    end if;

    if jsonb_typeof(result -> 'metadata') = 'object' then
        cleaned := (result -> 'metadata')
            - 'config_last_write_at'
            - 'config_last_write_source'
            - 'config_last_write_mode'
            - 'config_last_write_actor_id'
            - 'config_last_write_reason'
            - 'config_restored_from_version_id';
        result := jsonb_set(result, '{metadata}', cleaned, false);
    end if;

    if jsonb_typeof(result -> 'meta') = 'object' then
        cleaned := (result -> 'meta')
            - 'config_last_write_at'
            - 'config_last_write_source'
            - 'config_last_write_mode'
            - 'config_last_write_actor_id'
            - 'config_last_write_reason'
            - 'config_restored_from_version_id';
        result := jsonb_set(result, '{meta}', cleaned, false);
    end if;

    return result;
end;
$$;

create or replace function public.normalize_ticket_category_snapshot(payload jsonb)
returns jsonb
language sql
immutable
as $$
    select jsonb_build_object(
        'guild_id', coalesce(payload ->> 'guild_id', ''),
        'rows', coalesce(
            (
                select jsonb_agg(
                    cleaned
                    order by sort_order, slug, cleaned::text
                )
                from (
                    select
                        item
                            - 'id'
                            - 'created_at'
                            - 'updated_at' as cleaned,
                        coalesce((item ->> 'sort_order')::integer, 999) as sort_order,
                        coalesce(item ->> 'slug', '') as slug
                    from jsonb_array_elements(
                        coalesce(payload -> 'rows', '[]'::jsonb)
                    ) as item
                ) normalized_rows
            ),
            '[]'::jsonb
        )
    );
$$;

create or replace function public.capture_guild_config_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    payload jsonb;
    previous_payload jsonb;
    latest_snapshot jsonb;
    settings_payload jsonb;
    metadata_payload jsonb;
    resolved_guild_id text;
    resolved_source text;
    resolved_mode text;
    resolved_actor_id text;
    resolved_reason text;
begin
    payload := to_jsonb(new);
    resolved_guild_id := nullif(payload ->> 'guild_id', '');

    if resolved_guild_id is null then
        return new;
    end if;

    if tg_op = 'UPDATE' then
        previous_payload := to_jsonb(old);

        if public.normalize_guild_config_snapshot(payload)
           = public.normalize_guild_config_snapshot(previous_payload) then
            return new;
        end if;
    end if;

    select v.snapshot
      into latest_snapshot
      from public.guild_config_versions v
     where v.guild_id = resolved_guild_id
       and v.config_table = tg_table_name
     order by v.created_at desc, v.version_id desc
     limit 1;

    if latest_snapshot is not null
       and public.normalize_guild_config_snapshot(latest_snapshot)
           = public.normalize_guild_config_snapshot(payload) then
        return new;
    end if;

    settings_payload := coalesce(payload -> 'settings', '{}'::jsonb);
    metadata_payload := coalesce(payload -> 'metadata', '{}'::jsonb);

    resolved_source := coalesce(
        nullif(settings_payload ->> 'config_last_write_source', ''),
        nullif(metadata_payload ->> 'config_last_write_source', ''),
        'database'
    );
    resolved_mode := coalesce(
        nullif(settings_payload ->> 'config_last_write_mode', ''),
        nullif(metadata_payload ->> 'config_last_write_mode', '')
    );
    resolved_actor_id := coalesce(
        nullif(settings_payload ->> 'config_last_write_actor_id', ''),
        nullif(metadata_payload ->> 'config_last_write_actor_id', '')
    );
    resolved_reason := coalesce(
        nullif(settings_payload ->> 'config_last_write_reason', ''),
        nullif(metadata_payload ->> 'config_last_write_reason', '')
    );

    insert into public.guild_config_versions (
        guild_id,
        config_table,
        snapshot,
        source,
        mode,
        actor_id,
        reason,
        is_manual
    ) values (
        resolved_guild_id,
        tg_table_name,
        payload,
        resolved_source,
        resolved_mode,
        resolved_actor_id,
        resolved_reason,
        false
    );

    delete from public.guild_config_versions
    where version_id in (
        select version_id
        from public.guild_config_versions
        where guild_id = resolved_guild_id
          and config_table = tg_table_name
        order by created_at desc, version_id desc
        offset 50
    );

    return new;
end;
$$;

create or replace function public.capture_ticket_category_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    resolved_guild_id text;
    payload jsonb;
    category_rows jsonb;
    latest_snapshot jsonb;
begin
    -- Atomic restore RPC temporarily suppresses row-level intermediate versions.
    if coalesce(current_setting('dank_shield.skip_config_history', true), '') = '1' then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    if tg_op = 'DELETE' then
        resolved_guild_id := nullif(to_jsonb(old) ->> 'guild_id', '');
    else
        resolved_guild_id := nullif(to_jsonb(new) ->> 'guild_id', '');
    end if;

    if resolved_guild_id is null then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    select coalesce(
        jsonb_agg(
            to_jsonb(tc)
            order by
                coalesce((to_jsonb(tc) ->> 'sort_order')::integer, 999),
                coalesce(to_jsonb(tc) ->> 'slug', ''),
                coalesce(to_jsonb(tc) ->> 'id', '')
        ),
        '[]'::jsonb
    )
      into category_rows
      from public.ticket_categories tc
     where tc.guild_id = resolved_guild_id;

    payload := jsonb_build_object(
        'guild_id', resolved_guild_id,
        'rows', category_rows
    );

    select v.snapshot
      into latest_snapshot
      from public.guild_config_versions v
     where v.guild_id = resolved_guild_id
       and v.config_table = 'ticket_categories'
     order by v.created_at desc, v.version_id desc
     limit 1;

    if latest_snapshot is not null
       and public.normalize_ticket_category_snapshot(latest_snapshot)
           = public.normalize_ticket_category_snapshot(payload) then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    insert into public.guild_config_versions (
        guild_id,
        config_table,
        snapshot,
        source,
        mode,
        is_manual
    ) values (
        resolved_guild_id,
        'ticket_categories',
        payload,
        'ticket_categories',
        lower(tg_op),
        false
    );

    delete from public.guild_config_versions
    where version_id in (
        select version_id
        from public.guild_config_versions
        where guild_id = resolved_guild_id
          and config_table = 'ticket_categories'
        order by created_at desc, version_id desc
        offset 50
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

-- Restore a complete ticket-choice snapshot in one transaction. The dynamic
-- column handling preserves any compatible category/form columns present in the
-- deployment while leaving columns absent from an older snapshot unchanged on
-- matching rows and allowing table defaults on newly inserted missing fields.
create or replace function public.restore_ticket_categories_snapshot(
    p_guild_id text,
    p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    item jsonb;
    normalized_item jsonb;
    saved_slug text;
    update_clause text;
    insert_columns text;
    insert_values text;
    restored_rows jsonb;
begin
    if p_guild_id is null or btrim(p_guild_id) = '' then
        raise exception 'guild_id is required';
    end if;

    p_rows := coalesce(p_rows, '[]'::jsonb);
    if jsonb_typeof(p_rows) <> 'array' then
        raise exception 'ticket category snapshot rows must be a JSON array';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(p_rows) value
        where nullif(btrim(value ->> 'slug'), '') is null
    ) then
        raise exception 'ticket category snapshot contains a blank slug';
    end if;

    if exists (
        select 1
        from (
            select lower(btrim(value ->> 'slug')) as slug
            from jsonb_array_elements(p_rows) value
            group by lower(btrim(value ->> 'slug'))
            having count(*) > 1
        ) duplicate_slugs
    ) then
        raise exception 'ticket category snapshot contains duplicate slugs';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(p_rows) value
        where nullif(value ->> 'guild_id', '') is not null
          and value ->> 'guild_id' <> p_guild_id
    ) then
        raise exception 'ticket category snapshot contains a different guild_id';
    end if;

    -- This setting is transaction-local. If anything below fails, PostgreSQL
    -- rolls back every category mutation and the setting disappears with it.
    perform set_config('dank_shield.skip_config_history', '1', true);

    delete from public.ticket_categories tc
     where tc.guild_id = p_guild_id
       and not exists (
            select 1
            from jsonb_array_elements(p_rows) value
            where lower(btrim(value ->> 'slug')) = lower(tc.slug)
       );

    for item in select value from jsonb_array_elements(p_rows)
    loop
        saved_slug := btrim(item ->> 'slug');
        normalized_item := item || jsonb_build_object('guild_id', p_guild_id);

        if exists (
            select 1
            from public.ticket_categories tc
            where tc.guild_id = p_guild_id
              and lower(tc.slug) = lower(saved_slug)
        ) then
            select string_agg(
                format(
                    '%1$I = case when $1 ? %2$L then src.%1$I else tc.%1$I end',
                    c.column_name,
                    c.column_name
                ),
                ', '
                order by c.ordinal_position
            )
              into update_clause
              from information_schema.columns c
             where c.table_schema = 'public'
               and c.table_name = 'ticket_categories'
               and c.column_name not in (
                    'id',
                    'guild_id',
                    'slug',
                    'created_at',
                    'updated_at'
               );

            if update_clause is not null and update_clause <> '' then
                execute format(
                    'update public.ticket_categories tc set %s '
                    || 'from jsonb_populate_record(null::public.ticket_categories, $1) src '
                    || 'where tc.guild_id = $2 and lower(tc.slug) = lower($3)',
                    update_clause
                )
                using normalized_item, p_guild_id, saved_slug;
            end if;
        else
            select
                string_agg(format('%I', c.column_name), ', ' order by c.ordinal_position),
                string_agg(format('src.%I', c.column_name), ', ' order by c.ordinal_position)
              into insert_columns, insert_values
              from information_schema.columns c
             where c.table_schema = 'public'
               and c.table_name = 'ticket_categories'
               and c.column_name not in ('created_at', 'updated_at')
               and normalized_item ? c.column_name;

            if insert_columns is null or insert_columns = '' then
                raise exception 'ticket category snapshot row has no insertable columns';
            end if;

            begin
                execute format(
                    'insert into public.ticket_categories (%s) '
                    || 'select %s from jsonb_populate_record(null::public.ticket_categories, $1) src',
                    insert_columns,
                    insert_values
                )
                using normalized_item;
            exception when unique_violation then
                -- Historical UUID may collide only after external/manual data
                -- movement. Retry without the historical id so PostgreSQL uses
                -- the table default while preserving guild_id + slug identity.
                normalized_item := normalized_item - 'id';

                select
                    string_agg(format('%I', c.column_name), ', ' order by c.ordinal_position),
                    string_agg(format('src.%I', c.column_name), ', ' order by c.ordinal_position)
                  into insert_columns, insert_values
                  from information_schema.columns c
                 where c.table_schema = 'public'
                   and c.table_name = 'ticket_categories'
                   and c.column_name not in ('created_at', 'updated_at')
                   and normalized_item ? c.column_name;

                execute format(
                    'insert into public.ticket_categories (%s) '
                    || 'select %s from jsonb_populate_record(null::public.ticket_categories, $1) src',
                    insert_columns,
                    insert_values
                )
                using normalized_item;
            end;
        end if;
    end loop;

    perform set_config('dank_shield.skip_config_history', '0', true);

    select coalesce(
        jsonb_agg(
            to_jsonb(tc)
            order by
                coalesce((to_jsonb(tc) ->> 'sort_order')::integer, 999),
                coalesce(to_jsonb(tc) ->> 'slug', ''),
                coalesce(to_jsonb(tc) ->> 'id', '')
        ),
        '[]'::jsonb
    )
      into restored_rows
      from public.ticket_categories tc
     where tc.guild_id = p_guild_id;

    return jsonb_build_object(
        'guild_id', p_guild_id,
        'rows', restored_rows
    );
end;
$$;

revoke all on function public.restore_ticket_categories_snapshot(text, jsonb) from public;
grant execute on function public.restore_ticket_categories_snapshot(text, jsonb) to service_role;

-- Seed one baseline for already-configured canonical guild rows.
do $$
begin
    if to_regclass('public.guild_configs') is not null then
        execute $seed$
            insert into public.guild_config_versions (
                guild_id,
                config_table,
                snapshot,
                source,
                mode,
                is_manual
            )
            select
                gc.guild_id::text,
                'guild_configs',
                to_jsonb(gc),
                'migration_baseline',
                'baseline',
                false
            from public.guild_configs gc
            where not exists (
                select 1
                from public.guild_config_versions v
                where v.guild_id = gc.guild_id::text
                  and v.config_table = 'guild_configs'
            )
        $seed$;
    end if;
end;
$$;

-- Seed one baseline for guilds still stored in the legacy fallback table.
do $$
begin
    if to_regclass('public.guild_config') is not null then
        execute $seed$
            insert into public.guild_config_versions (
                guild_id,
                config_table,
                snapshot,
                source,
                mode,
                is_manual
            )
            select
                gc.guild_id::text,
                'guild_config',
                to_jsonb(gc),
                'migration_baseline',
                'baseline',
                false
            from public.guild_config gc
            where not exists (
                select 1
                from public.guild_config_versions v
                where v.guild_id = gc.guild_id::text
                  and v.config_table = 'guild_config'
            )
        $seed$;
    end if;
end;
$$;

-- Seed ticket-choice baselines for guilds that already have category rows.
do $$
begin
    if to_regclass('public.ticket_categories') is not null then
        execute $seed$
            insert into public.guild_config_versions (
                guild_id,
                config_table,
                snapshot,
                source,
                mode,
                is_manual
            )
            select
                tc.guild_id::text,
                'ticket_categories',
                jsonb_build_object(
                    'guild_id',
                    tc.guild_id::text,
                    'rows',
                    jsonb_agg(
                        to_jsonb(tc)
                        order by
                            coalesce((to_jsonb(tc) ->> 'sort_order')::integer, 999),
                            coalesce(to_jsonb(tc) ->> 'slug', ''),
                            coalesce(to_jsonb(tc) ->> 'id', '')
                    )
                ),
                'migration_baseline',
                'baseline',
                false
            from public.ticket_categories tc
            where not exists (
                select 1
                from public.guild_config_versions v
                where v.guild_id = tc.guild_id::text
                  and v.config_table = 'ticket_categories'
            )
            group by tc.guild_id
        $seed$;
    end if;
end;
$$;

-- Seed an empty ticket-choice baseline for configured guilds with no categories.
do $$
begin
    if to_regclass('public.ticket_categories') is not null
       and to_regclass('public.guild_configs') is not null then
        execute $seed$
            insert into public.guild_config_versions (
                guild_id,
                config_table,
                snapshot,
                source,
                mode,
                is_manual
            )
            select
                gc.guild_id::text,
                'ticket_categories',
                jsonb_build_object(
                    'guild_id', gc.guild_id::text,
                    'rows', '[]'::jsonb
                ),
                'migration_baseline',
                'baseline',
                false
            from public.guild_configs gc
            where not exists (
                select 1
                from public.guild_config_versions v
                where v.guild_id = gc.guild_id::text
                  and v.config_table = 'ticket_categories'
            )
        $seed$;
    end if;
end;
$$;

-- Same empty-baseline protection for guilds living only in legacy guild_config.
do $$
begin
    if to_regclass('public.ticket_categories') is not null
       and to_regclass('public.guild_config') is not null then
        execute $seed$
            insert into public.guild_config_versions (
                guild_id,
                config_table,
                snapshot,
                source,
                mode,
                is_manual
            )
            select
                gc.guild_id::text,
                'ticket_categories',
                jsonb_build_object(
                    'guild_id', gc.guild_id::text,
                    'rows', '[]'::jsonb
                ),
                'migration_baseline',
                'baseline',
                false
            from public.guild_config gc
            where not exists (
                select 1
                from public.guild_config_versions v
                where v.guild_id = gc.guild_id::text
                  and v.config_table = 'ticket_categories'
            )
        $seed$;
    end if;
end;
$$;

-- Attach to the canonical table when present.
do $$
begin
    if to_regclass('public.guild_configs') is not null then
        execute 'drop trigger if exists trg_capture_guild_config_version on public.guild_configs';
        execute '
            create trigger trg_capture_guild_config_version
            after insert or update on public.guild_configs
            for each row
            execute function public.capture_guild_config_version()
        ';
    end if;
end;
$$;

-- Attach to the historical fallback table too, when present. History records
-- remain isolated by config_table, so a legacy snapshot cannot restore into the
-- canonical table (or vice versa).
do $$
begin
    if to_regclass('public.guild_config') is not null then
        execute 'drop trigger if exists trg_capture_guild_config_version on public.guild_config';
        execute '
            create trigger trg_capture_guild_config_version
            after insert or update on public.guild_config
            for each row
            execute function public.capture_guild_config_version()
        ';
    end if;
end;
$$;

-- Version the active ticket choices and category-stored form configuration.
do $$
begin
    if to_regclass('public.ticket_categories') is not null then
        execute 'drop trigger if exists trg_capture_ticket_category_version on public.ticket_categories';
        execute '
            create trigger trg_capture_ticket_category_version
            after insert or update or delete on public.ticket_categories
            for each row
            execute function public.capture_ticket_category_version()
        ';
    end if;
end;
$$;